# Generated by Django 3.1.4 on 2020-12-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='account',
        ),
    ]
