# Generated by Django 3.1.4 on 2020-12-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201225_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='./store_images/placeholder.png', upload_to='media'),
        ),
    ]
