# Generated by Django 3.1.4 on 2020-12-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201225_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='./media/placeholder.png', upload_to=''),
        ),
    ]
