# Generated by Django 3.1.4 on 2020-12-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201225_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.TextField(default='user'),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.TextField(default='qwerty'),
        ),
    ]
