# Generated by Django 3.1.4 on 2020-12-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201227_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='../media/placeholder.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
