# Generated by Django 3.1.4 on 2020-12-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201228_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('manager', 'Can Manage Items')]},
        ),
    ]
